
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKNENTERO = 5;
  public static final int TKNNEGACION = 49;
  public static final int TKNINT = 55;
  public static final int TKNVERDADERO = 58;
  public static final int TKNCOMA = 52;
  public static final int TKNMODIGUAL = 40;
  public static final int TKNFINESTRUCTURA = 20;
  public static final int TKNRESTA = 29;
  public static final int TKNVARIABLE = 4;
  public static final int TKNID = 63;
  public static final int TKNDOSPUNTOS = 3;
  public static final int TKNSUMAIGUAL = 36;
  public static final int TKNPROCEDIMIENTOS = 14;
  public static final int TKNSIMBOLOVALOR = 57;
  public static final int TKNPARENTESISABRE = 50;
  public static final int TKNIGUAL = 35;
  public static final int TKNRESTAIGUAL = 37;
  public static final int TKNY = 47;
  public static final int TKNIGUALOG = 41;
  public static final int TKNMODULO = 32;
  public static final int TKNDIVISION = 31;
  public static final int TKNCADENA = 56;
  public static final int TKNPARA = 25;
  public static final int TKNLOGICO = 9;
  public static final int TKNFUNCIONES = 13;
  public static final int EOF = 0;
  public static final int TKNMULTIGUAL = 38;
  public static final int TKNHORAVALOR = 61;
  public static final int TKNO = 48;
  public static final int TKNROMPER = 27;
  public static final int TKNDISTINTO = 42;
  public static final int TKNCDPRINCIPAL = 12;
  public static final int error = 1;
  public static final int TKNMENOR = 44;
  public static final int TKNDATORFC = 53;
  public static final int TKNSIMBOLO = 7;
  public static final int TKNCURP = 11;
  public static final int TKNDEVOLVER = 16;
  public static final int ERROR = 64;
  public static final int TKNFUNCION = 15;
  public static final int TKNMENORIGUAL = 46;
  public static final int TKNMAYOR = 43;
  public static final int TKNDIVIGUAL = 39;
  public static final int TKNENTONCES = 23;
  public static final int TKNPUNTO = 21;
  public static final int TKNDATOCURP = 54;
  public static final int TKNINCREMENTO = 33;
  public static final int TKNFECHAHORAVALOR = 62;
  public static final int TKNRFC = 10;
  public static final int TKNFALSO = 59;
  public static final int TKNMAYORIGUAL = 45;
  public static final int TKNMIENTRAS = 26;
  public static final int TKNPROCEDIMIENTO = 18;
  public static final int TKNINICIOESTRUCTURA = 19;
  public static final int TKNDECREMENTO = 34;
  public static final int TKNSINO = 24;
  public static final int TKNPARENTESISCIERRA = 51;
  public static final int TKNSI = 22;
  public static final int TKNTEXTO = 8;
  public static final int TKNVARIABLES = 2;
  public static final int TKNFECHAVALOR = 60;
  public static final int TKNCOMO = 17;
  public static final int TKNSUMA = 28;
  public static final int TKNDECIMAL = 6;
  public static final int TKNMULTIPLICACION = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TKNVARIABLES",
  "TKNDOSPUNTOS",
  "TKNVARIABLE",
  "TKNENTERO",
  "TKNDECIMAL",
  "TKNSIMBOLO",
  "TKNTEXTO",
  "TKNLOGICO",
  "TKNRFC",
  "TKNCURP",
  "TKNCDPRINCIPAL",
  "TKNFUNCIONES",
  "TKNPROCEDIMIENTOS",
  "TKNFUNCION",
  "TKNDEVOLVER",
  "TKNCOMO",
  "TKNPROCEDIMIENTO",
  "TKNINICIOESTRUCTURA",
  "TKNFINESTRUCTURA",
  "TKNPUNTO",
  "TKNSI",
  "TKNENTONCES",
  "TKNSINO",
  "TKNPARA",
  "TKNMIENTRAS",
  "TKNROMPER",
  "TKNSUMA",
  "TKNRESTA",
  "TKNMULTIPLICACION",
  "TKNDIVISION",
  "TKNMODULO",
  "TKNINCREMENTO",
  "TKNDECREMENTO",
  "TKNIGUAL",
  "TKNSUMAIGUAL",
  "TKNRESTAIGUAL",
  "TKNMULTIGUAL",
  "TKNDIVIGUAL",
  "TKNMODIGUAL",
  "TKNIGUALOG",
  "TKNDISTINTO",
  "TKNMAYOR",
  "TKNMENOR",
  "TKNMAYORIGUAL",
  "TKNMENORIGUAL",
  "TKNY",
  "TKNO",
  "TKNNEGACION",
  "TKNPARENTESISABRE",
  "TKNPARENTESISCIERRA",
  "TKNCOMA",
  "TKNDATORFC",
  "TKNDATOCURP",
  "TKNINT",
  "TKNCADENA",
  "TKNSIMBOLOVALOR",
  "TKNVERDADERO",
  "TKNFALSO",
  "TKNFECHAVALOR",
  "TKNHORAVALOR",
  "TKNFECHAHORAVALOR",
  "TKNID",
  "ERROR"
  };
}

